version: '3.8'

services:
  frontend:
    build:
      context: ./xoohoox-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./xoohoox-frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
    depends_on:
      - api

  api:
    build:
      context: ./xoohoox-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./xoohoox-backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres@host.docker.internal:5432/xoohoox
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=development
    depends_on:
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: 