"""Initial migration

Revision ID: 449c652c6fa3
Revises: 
Create Date: 2025-04-11 14:01:53.929810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '449c652c6fa3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_tracking',
    sa.Column('batch_id', sa.String(length=10), nullable=False),
    sa.Column('arrival_date', sa.DateTime(), nullable=False),
    sa.Column('fruit_type', sa.Enum('ORANGE', 'APPLE', 'GRAPE', 'PINEAPPLE', 'MANGO', 'OTHER', name='fruittype'), nullable=False),
    sa.Column('supplier_name', sa.String(length=100), nullable=False),
    sa.Column('supplier_batch_id', sa.String(length=50), nullable=True),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('quality_grade', sa.Enum('A', 'B', 'C', 'REJECTED', name='qualitygrade'), nullable=False),
    sa.Column('storage_location', sa.String(length=50), nullable=True),
    sa.Column('storage_conditions', sa.Text(), nullable=True),
    sa.Column('initial_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'IN_STORAGE', 'IN_PROCESSING', 'COMPLETED', 'REJECTED', name='batchstatus'), nullable=False),
    sa.Column('processing_start_date', sa.DateTime(), nullable=True),
    sa.Column('processing_end_date', sa.DateTime(), nullable=True),
    sa.Column('final_product_type', sa.Enum('JUICE', 'CONCENTRATE', 'PUREE', 'OTHER', name='finalproducttype'), nullable=True),
    sa.Column('final_product_quantity', sa.Float(), nullable=True),
    sa.Column('quality_issues', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_tracking_batch_id'), 'batch_tracking', ['batch_id'], unique=True)
    op.create_index(op.f('ix_batch_tracking_id'), 'batch_tracking', ['id'], unique=False)
    op.create_table('juicing_input_log',
    sa.Column('log_id', sa.String(length=10), nullable=False),
    sa.Column('batch_id', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('operator_id', sa.String(length=50), nullable=False),
    sa.Column('equipment_id', sa.String(length=50), nullable=False),
    sa.Column('input_quantity_kg', sa.Float(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('pressure_bar', sa.Float(), nullable=False),
    sa.Column('duration_minutes', sa.Float(), nullable=False),
    sa.Column('output_quantity_l', sa.Float(), nullable=False),
    sa.Column('brix_reading', sa.Float(), nullable=False),
    sa.Column('ph_level', sa.Float(), nullable=False),
    sa.Column('turbidity_ntu', sa.Float(), nullable=False),
    sa.Column('process_notes', sa.Text(), nullable=True),
    sa.Column('quality_issues', sa.Text(), nullable=True),
    sa.Column('process_status', sa.Enum('STARTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='processstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_tracking.batch_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_juicing_input_log_id'), 'juicing_input_log', ['id'], unique=False)
    op.create_index(op.f('ix_juicing_input_log_log_id'), 'juicing_input_log', ['log_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_juicing_input_log_log_id'), table_name='juicing_input_log')
    op.drop_index(op.f('ix_juicing_input_log_id'), table_name='juicing_input_log')
    op.drop_table('juicing_input_log')
    op.drop_index(op.f('ix_batch_tracking_id'), table_name='batch_tracking')
    op.drop_index(op.f('ix_batch_tracking_batch_id'), table_name='batch_tracking')
    op.drop_table('batch_tracking')
    # ### end Alembic commands ###
